name: Build Addon

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java 17 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Rechte für Gradle setzen
        run: chmod +x ./gradlew

      - name: Build ausführen
        run: ./gradlew build --no-daemon
